SKILL_BANKS = {
    "general": [
        "leadership",
        "communication",
        "collaboration",
        "problem solving",
        "project management",
        "customer service",
        "analysis",
        "reporting",
        "training",
        "documentation",
        "process improvement",
        "stakeholder management",
    ],

    "technology": [
        "python",
        "java",
        "javascript",
        "typescript",
        "sql",
        "postgresql",
        "mysql",
        "mongodb",
        "redis",
        "fastapi",
        "flask",
        "django",
        "spring boot",
        "node.js",
        "react",
        "next.js",
        "docker",
        "kubernetes",
        "aws",
        "azure",
        "gcp",
        "git",
        "github",
        "ci/cd",
        "rest api",
        "microservices",
        "system design",
        "data structures",
        "algorithms",
        "oop",
    ],

    "ai_engineer": [
        "python",
        "machine learning",
        "deep learning",
        "natural language processing",
        "nlp",
        "large language models",
        "llm",
        "rag",
        "embeddings",
        "vector database",
        "chromadb",
        "pinecone",
        "langchain",
        "langgraph",
        "openai",
        "hugging face",
        "transformers",
        "pytorch",
        "tensorflow",
        "fastapi",
        "mlops",
        "model deployment",
        "prompt engineering",
        "agents",
        "evaluation",
    ],

    "ml_engineer": [
        "python",
        "machine learning",
        "deep learning",
        "supervised learning",
        "unsupervised learning",
        "classification",
        "regression",
        "feature engineering",
        "model training",
        "model evaluation",
        "scikit-learn",
        "pytorch",
        "tensorflow",
        "pandas",
        "numpy",
        "matplotlib",
        "mlops",
        "model deployment",
        "docker",
        "aws",
        "data pipelines",
        "experimentation",
    ],

    "data_analyst": [
        "sql",
        "excel",
        "python",
        "tableau",
        "power bi",
        "data visualization",
        "dashboard",
        "reporting",
        "data cleaning",
        "data analysis",
        "statistics",
        "pandas",
        "numpy",
        "business intelligence",
        "kpi",
        "forecasting",
    ],

    "education": [
        "lesson planning",
        "classroom management",
        "curriculum development",
        "student assessment",
        "parent communication",
        "differentiated instruction",
        "teaching",
        "training",
        "learning outcomes",
        "student engagement",
        "instructional design",
    ],

    "hr": [
        "recruiting",
        "talent acquisition",
        "onboarding",
        "employee relations",
        "hris",
        "compliance",
        "benefits administration",
        "performance management",
        "training",
        "policy",
        "workforce planning",
    ],

    "marketing": [
        "seo",
        "content strategy",
        "google analytics",
        "campaign management",
        "email marketing",
        "social media",
        "brand management",
        "copywriting",
        "conversion rate",
        "market research",
        "crm",
    ],

    "finance": [
        "financial modeling",
        "budgeting",
        "forecasting",
        "excel",
        "risk analysis",
        "reporting",
        "accounting",
        "variance analysis",
        "financial statements",
        "compliance",
        "power bi",
    ],

    "healthcare": [
        "patient care",
        "medical records",
        "hipaa",
        "clinical documentation",
        "care coordination",
        "healthcare compliance",
        "patient communication",
        "scheduling",
        "insurance verification",
    ],

    "sales": [
        "lead generation",
        "crm",
        "salesforce",
        "pipeline management",
        "cold outreach",
        "negotiation",
        "client relationship",
        "quota achievement",
        "account management",
        "prospecting",
    ],

    "operations": [
        "process improvement",
        "vendor management",
        "logistics",
        "inventory management",
        "scheduling",
        "workflow optimization",
        "quality assurance",
        "reporting",
        "cross-functional collaboration",
    ],
}


def get_skill_bank(industry: str) -> list[str]:
    normalized_industry = industry.lower().strip()

    return SKILL_BANKS.get(normalized_industry, SKILL_BANKS["general"])
